stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Сборка проекта..."
    - npm i -g pnpm
    - pnpm i
    - pnpm build
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
  script:
    - echo "Деплой на сервер..."
    - ssh root@$REMOTE_HOST "
      cd $REMOTE_DIR &&
      git pull origin master &&
      pnpm i &&
      if pnpm build; then
        echo 'Сборка успешна, перезапуск приложения...' &&
        if screen -list | grep -q 'fftms'; then
          screen -S fftms -X quit;
        fi &&
        screen -S fftms -dm bash -c 'pnpm start';
      else
        echo 'Ошибка сборки, откат до последней успешной версии...' &&
        git reset --hard HEAD~1 &&
        if screen -list | grep -q 'fftms'; then
          screen -S fftms -X quit;
        fi &&
        screen -S fftms -dm bash -c 'pnpm start';
      fi
      "
  only:
    - master
  dependencies:
    - build
