services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: pnpm start
